### ISSUE TITLE
Our mission - secondary hero text

### ISSUE THREAD

**Issue by lizzie-madebyon** [on-associates/voyage-youth-webflow-scripts#5]
![Image](https://user-images.githubusercontent.com/89518778/258431119-2cda05e6-31be-4a18-acc7-9576ecf1dae1.png)

![Image](https://user-images.githubusercontent.com/89518778/258431162-edb4949d-e826-4d90-ae6b-257f18276d58.png)

**Comment by MilanVetnic** [comment]
Updated
